services:
  - type: web
    name: prasta-solusi-indonesia
    env: php
    plan: free
    buildCommand: "composer install --no-dev --optimize-autoloader && cp .env.example .env && php artisan key:generate"
    startCommand: "apache2-run"
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        generateValue: true
